server:
  port: 35864

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://server-kayak.959696.xyz:3306/kayak_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
#    url: jdbc:mysql://10.0.0.50:3306/kayak_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: x22OSaQn3nI9pgoH40x
